REPRODUCTION_COOLDOWN = 300  # Frames between allowed reproductions
REST_ENERGY_GAIN = 0.5  # Energy gained per frame while resting (not moving)
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
CREATURE_COUNT = 15
FOOD_COUNT = 100
MUTATION_RATE = 0.2
ENERGY_COST_PER_UNIT = .1
FOOD_SPAWN_INTERVAL = 120
VISION_MIN = 30
VISION_MAX = 130
SPEED_MIN = 0.5
SPEED_MAX = 1.5
HUNGER_MAX = 400
HUNGER_THRESHOLD = 200
THIRST_MAX = 400
THIRST_THRESHOLD = 200
LOG_INTERVAL = 60  # How often to log history (in frames)

# Lake settings (centered)
LAKE_WIDTH = 300
LAKE_HEIGHT = 200
LAKE_X = (SCREEN_WIDTH - LAKE_WIDTH) // 2
LAKE_Y = (SCREEN_HEIGHT - LAKE_HEIGHT) // 2